# -*- coding: utf-8 -*-
"""
/***************************************************************************
 Latlngcalc
                                 A QGIS plugin
 Allows conversion of latitude and longitude between decimal degrees and DMS
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2020-12-26
        copyright            : (C) 2020 by Reginald Carlier
        email                : reginald.carlier@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load Latlngcalc class from file Latlngcalc.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .lstlngcalc import Latlngcalc
    return Latlngcalc(iface)
